In [1]:
import pandas as pd

pd.read_csv("auto_exps_state.csv", index_col=[0,1], header=[0,1,2])

Datasets                 ETTh1
Shaping Process       identity
Shaping Window             N/A
Horizons Models
96       AutoTFT          True
         AutoTSMixerx     True
         AutoGRU          True
         AutoTCN          True
         AutoTiDE         True
         AutoBiTCN        True
         AutoDeepNPTS     True
         AutoLSTM         True
         AutoNHITS        True
         AutoMLP          True
         AutoNBEATSx      True
192      AutoTFT          True
         AutoTSMixerx     True
         AutoGRU          True
         AutoTCN          True
         AutoTiDE         True
         AutoBiTCN        True
         AutoDeepNPTS     True
         AutoLSTM         True
         AutoNHITS        True
         AutoMLP          True
         AutoNBEATSx      True
336      AutoTFT          True
         AutoTSMixerx     True
         AutoGRU          True
         AutoTCN          True
         AutoTiDE         True
         AutoBiTCN        True
         AutoDeepNPTS     True
         AutoLSTM         True
         AutoNHITS        True
         AutoMLP          True
         AutoNBEATSx      True
720      AutoTFT          True
         AutoTSMixerx     True
         AutoGRU          True
         AutoTCN          True
         AutoTiDE         True
         AutoBiTCN        True
         AutoDeepNPTS     True
         AutoLSTM         True
         AutoNHITS        True
         AutoMLP          True
         AutoNBEATSx      True

In [20]:
import pandas as pd

df_exps_state = pd.read_csv("exps_state.csv", index_col=[0,1], header=[0,1,2])

# df_exps_state.columns.set_levels(df_exps_state.columns.get_level_values("Shaping Window").astype(int), level="Shaping Window")

df_exps_state

Datasets          ETTh1                                                      \
Shaping Process   pfarm                         prollcorr
Shaping Window      501   751  1001  1251  1501       501   751  1001  1251
Horizons Models
96       TFT       True  True  True  True  True      True  True  True  True
         TSMixerx  True  True  True  True  True      True  True  True  True
         GRU       True  True  True  True  True      True  True  True  True
         TCN       True  True  True  True  True      True  True  True  True
         TiDE      True  True  True  True  True      True  True  True  True
         BiTCN     True  True  True  True  True      True  True  True  True
         DeepNPTS  True  True  True  True  True      True  True  True  True
         LSTM      True  True  True  True  True      True  True  True  True
         NHITS     True  True  True  True  True      True  True  True  True
         MLP       True  True  True  True  True      True  True  True  True
         NBEATSx   True  True  True  True  True      True  True  True  True
192      TFT       True  True  True  True  True      True  True  True  True
         TSMixerx  True  True  True  True  True      True  True  True  True
         GRU       True  True  True  True  True      True  True  True  True
         TCN       True  True  True  True  True      True  True  True  True
         TiDE      True  True  True  True  True      True  True  True  True
         BiTCN     True  True  True  True  True      True  True  True  True
         DeepNPTS  True  True  True  True  True      True  True  True  True
         LSTM      True  True  True  True  True      True  True  True  True
         NHITS     True  True  True  True  True      True  True  True  True
         MLP       True  True  True  True  True      True  True  True  True
         NBEATSx   True  True  True  True  True      True  True  True  True
336      TFT       True  True  True  True  True      True  True  True  True
         TSMixerx  True  True  True  True  True      True  True  True  True
         GRU       True  True  True  True  True      True  True  True  True
         TCN       True  True  True  True  True      True  True  True  True
         TiDE      True  True  True  True  True      True  True  True  True
         BiTCN     True  True  True  True  True      True  True  True  True
         DeepNPTS  True  True  True  True  True      True  True  True  True
         LSTM      True  True  True  True  True      True  True  True  True
         NHITS     True  True  True  True  True      True  True  True  True
         MLP       True  True  True  True  True      True  True  True  True
         NBEATSx   True  True  True  True  True      True  True  True  True
720      TFT       True  True  True  True  True      True  True  True  True
         TSMixerx  True  True  True  True  True      True  True  True  True
         GRU       True  True  True  True  True      True  True  True  True
         TCN       True  True  True  True  True      True  True  True  True
         TiDE      True  True  True  True  True      True  True  True  True
         BiTCN     True  True  True  True  True      True  True  True  True
         DeepNPTS  True  True  True  True  True      True  True  True  True
         LSTM      True  True  True  True  True      True  True  True  True
         NHITS     True  True  True  True  True      True  True  True  True
         MLP       True  True  True  True  True      True  True  True  True
         NBEATSx   True  True  True  True  True      True  True  True  True

Datasets                 ...                                                  \
Shaping Process          ... ipentropy                   ipmutual_info
Shaping Window     1501  ...       751  1001  1251  1501           501   751
Horizons Models          ...
96       TFT       True  ...      True  True  True  True          True  True
         TSMixerx  True  ...      True  True  True  True          True  True
         GRU       True  ...      True  True  True  True          True  True
         TCN       True  ...      True  True  True  True          True  True
         TiDE      True  ...      True  True  True  True          True  True
         BiTCN     True  ...      True  True  True  True          True  True
         DeepNPTS  True  ...      True  True  True  True          True  True
         LSTM      True  ...      True  True  True  True          True  True
         NHITS     True  ...      True  True  True  True          True  True
         MLP       True  ...      True  True  True  True          True  True
         NBEATSx   True  ...      True  True  True  True          True  True
192      TFT       True  ...      True  True  True  True          True  True
         TSMixerx  True  ...      True  True  True  True          True  True
         GRU       True  ...      True  True  True  True          True  True
         TCN       True  ...      True  True  True  True          True  True
         TiDE      True  ...      True  True  True  True          True  True
         BiTCN     True  ...      True  True  True  True          True  True
         DeepNPTS  True  ...      True  True  True  True          True  True
         LSTM      True  ...      True  True  True  True          True  True
         NHITS     True  ...      True  True  True  True          True  True
         MLP       True  ...      True  True  True  True          True  True
         NBEATSx   True  ...      True  True  True  True          True  True
336      TFT       True  ...      True  True  True  True          True  True
         TSMixerx  True  ...      True  True  True  True          True  True
         GRU       True  ...      True  True  True  True          True  True
         TCN       True  ...      True  True  True  True          True  True
         TiDE      True  ...      True  True  True  True          True  True
         BiTCN     True  ...      True  True  True  True          True  True
         DeepNPTS  True  ...      True  True  True  True          True  True
         LSTM      True  ...      True  True  True  True          True  True
         NHITS     True  ...      True  True  True  True          True  True
         MLP       True  ...      True  True  True  True          True  True
         NBEATSx   True  ...      True  True  True  True          True  True
720      TFT       True  ...      True  True  True  True          True  True
         TSMixerx  True  ...      True  True  True  True          True  True
         GRU       True  ...      True  True  True  True          True  True
         TCN       True  ...      True  True  True  True          True  True
         TiDE      True  ...      True  True  True  True          True  True
         BiTCN     True  ...      True  True  True  True          True  True
         DeepNPTS  True  ...      True  True  True  True          True  True
         LSTM      True  ...      True  True  True  True          True  True
         NHITS     True  ...      True  True  True  True          True  True
         MLP       True  ...      True  True  True  True          True  True
         NBEATSx   True  ...      True  True  True  True          True  True

Datasets
Shaping Process                     identity
Shaping Window     1001  1251  1501      N/A
Horizons Models
96       TFT       True  True  True    False
         TSMixerx  True  True  True    False
         GRU       True  True  True    False
         TCN       True  True  True    False
         TiDE      True  True  True    False
         BiTCN     True  True  True    False
         DeepNPTS  True  True  True    False
         LSTM      True  True  True    False
         NHITS     True  True  True    False
         MLP       True  True  True    False
         NBEATSx   True  True  True    False
192      TFT       True  True  True    False
         TSMixerx  True  True  True    False
         GRU       True  True  True    False
         TCN       True  True  True    False
         TiDE      True  True  True    False
         BiTCN     True  True  True    False
         DeepNPTS  True  True  True    False
         LSTM      True  True  True    False
         NHITS     True  True  True    False
         MLP       True  True  True    False
         NBEATSx   True  True  True    False
336      TFT       True  True  True    False
         TSMixerx  True  True  True    False
         GRU       True  True  True    False
         TCN       True  True  True    False
         TiDE      True  True  True    False
         BiTCN     True  True  True    False
         DeepNPTS  True  True  True    False
         LSTM      True  True  True    False
         NHITS     True  True  True    False
         MLP       True  True  True    False
         NBEATSx   True  True  True    False
720      TFT       True  True  True    False
         TSMixerx  True  True  True    False
         GRU       True  True  True    False
         TCN       True  True  True    False
         TiDE      True  True  True    False
         BiTCN     True  True  True    False
         DeepNPTS  True  True  True    False
         LSTM      True  True  True    False
         NHITS     True  True  True    False
         MLP       True  True  True    False
         NBEATSx   True  True  True    False

[44 rows x 51 columns]

In [ ]:
df_exps_state.loc[(720, "TFT"), ('ETTh1', 'ipmutual_info', 1501)]